### ISSUE TITLE
Cannot login with google account

### ISSUE THREAD

**Issue by Xelwon** [omkarmoghe/Pokemap#299] opened 2016-07-28 10:13 UTC
It happens me from dev-rev389 to dev-rev396. Before don`t.

When I press google account button the app always sais me. 'Failed PTC login.'

I have galaxy S4 andriod 5.0.1.

**Comment by pr0letariat** [comment] 2016-07-28 10:21
Duplicate of https://github.com/omkarmoghe/Pokemap/issues/287

**Comment by Gennocyde** [comment] 2016-07-28 16:32
Rev417 both Google and PTC wont login but  Rev415 allows PTC login

**Comment by Lb141** [comment] 2016-07-28 16:51
Says google login failed still, i read somewhere you found a new way for google log in is that going to be a thing?

**Closed as completed** 2016-07-28 20:59 UTC
