### ISSUE TITLE
.

### ISSUE THREAD

**Issue by DaeFolf** [omkarmoghe/Pokemap#109] opened 2016-07-24 16:52 UTC
.

**Comment by ManojMadanmohan** [comment] 2016-07-24 16:54
Possibly a duplicate of #96 , which itself is a duplicate of #92

**Comment by omkarmoghe** [comment] 2016-07-24 16:54
We're currently working on widening the area without getting accounts banned for gps spoofing. stay tuned!

**Comment by botard89** [comment] 2016-07-25 02:10
Hey. I have been following this for a little bit now, watching progress, and it is all very fascinating. I wanted to personally ask on the subject of radius, there is the python 2.7.X version of something similar to this and was wondering if there might be a feature or optional feature where the steps (-st) could be customized? I like having a whole area to see what is in a town for example. Thanks and awesome job everyone.

**Comment by rohanjain1** [comment] 2016-07-25 10:10
While it is possible to expand the search area indefinitely, it is not recommended. For now we'll be enforcing a cap on the max searchable area like the py version. If the demand seems strong enough we'll deliberate over a logical way to achieve 'n' step areas, without completely breaking the system.

**Comment by comann** [comment] 2016-07-26 21:04
Done.

**Closed as completed by comann** 2016-07-26 21:04 UTC
Labels: enhancement
