### ISSUE TITLE
Bug with the background service?

### ISSUE THREAD

**Issue by Giggitybyte** [omkarmoghe/Pokemap#178] opened 2016-07-26 11:07 UTC
I'm not really sure how to describe this bug, it's pretty weird. See the screenshot and videos below.

<details> 
  <summary>

Click to see screenshot and videos</summary>

  ![screenshot_2016-07-26-03-22-19](https://cloud.githubusercontent.com/assets/19187704/17135221/79b63676-52e3-11e6-8e47-f5abd458c69c.png)
## [Video part 2](https://youtu.be/BAoUgv3IoWU)

</details>

~~My guess is that something is happening while removing a Pokemon.~~ It actually seems to be caused by the background service!

**Comment by rohanjain1** [comment] 2016-07-26 11:12
Pretty professional level bug reporting :D 
Thanks for bringing it to our notice. Will have a look

**Comment by Giggitybyte** [comment] 2016-07-26 11:30
Thanks! I try my best! :smiley:

Hope you guys squash this bug good!

**Comment by Giggitybyte** [comment] 2016-07-26 12:32
Heyo @rohanjain1, quick update.

Somehow got it to happen again. Not really sure how I did it, wasn't even paying attention.
[Another video](https://youtu.be/ysqwuA0KzDs)

Made sure to grab the logcat once I realized it had happened.
[App specific log](https://github.com/omkarmoghe/Pokemap/files/383739/logcat_app.txt) via Android Studio.
[Full logcat](https://github.com/omkarmoghe/Pokemap/files/383738/logcat3.txt) (that's a lot of lines!)

One thing I noticed while I had the logcat going (which is probably unrelated) were the following lines that were spammed about 10 times a second whenever the map was not actually shown; e.g. Screen-off,  while in settings, app switcher, backgrounded, etc.
`No subscribers registered for event class com.omkarmoghe.pokemap.models.events.PokestopsEvent`
`No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent`


If you guys need anything more, let me know.

**Comment by Giggitybyte** [comment] 2016-07-26 12:40
Heyo @rohanjain1, quick update.

Somehow got it to happen again. Not really sure how I did it, wasn't even paying attention.
[Another video](https://youtu.be/ysqwuA0KzDs).

Made sure to grab the logcat once I realized it had happened.
[App specific log](https://github.com/omkarmoghe/Pokemap/files/383739/logcat_app.txt) via Android Studio.
[Full logcat](https://github.com/omkarmoghe/Pokemap/files/383738/logcat3.txt) (that's a lot of lines!)

One thing I noticed while I had the logcat going (which is probably unrelated) were the following lines that were spammed about 10 times a second:
`No subscribers registered for event class com.omkarmoghe.pokemap.models.events.PokestopsEvent`
`No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent`
These lines came up whenever the map was not actually shown; e.g. Screen-off,  while in settings, app switcher, backgrounded, etc.

If you guys need anything more, let me know.

**Comment by kyr0** [comment] 2016-07-26 13:17
Possible duplicate of #173 ?

**Comment by vidarr101** [comment] 2016-07-26 13:57
I submitted a PR for fixing the event spam.  That should make it easier to find the real issue.

**Comment by Giggitybyte** [comment] 2016-07-26 22:51
Looks like my guess about it being a removal problem was wrong. After playing around with things more, the problem seems to be the background service. I can scan and clear as much as I please when the background service is disabled. However, once I turn the background service on and leave the app and come back, the bug occurs.

**Comment by Giggitybyte** [comment] 2016-07-27 05:10
@rohanjain1 @xyber3364 @s7092910 @comann

**Comment by rohanjain1** [comment] 2016-07-27 10:53
@Giggitybyte thanks :+1:  dev is going on a lot faster than testing atm, but will keep an eye out for this bugger.

**Comment by Giggitybyte** [comment] 2016-07-27 20:04
No problem! You guys seem pretty busy!

**Comment by jLynx** [comment] 2016-08-27 01:22
Please re-open the issues if this is not fixed in the current release

**Closed as completed by jLynx** 2016-08-27 01:22 UTC
