### ISSUE TITLE
[Enhancement] Add method to check: "is PTC server available or not?"

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#296] opened 2016-07-28 08:58 UTC
Add any method to check: "is PTC server available or not?"
Run the method after clicking on "Login with PTC" in login screen, if it's not available show a dialog instead of trying to log in.
![screenshot20](https://cloud.githubusercontent.com/assets/3495165/17206876/947959ec-54ba-11e6-90bd-7ba051375560.png)

**Comment by CarstenHouweling** [comment] 2016-07-28 09:12
Look at #257

**Comment by Giggitybyte** [comment] 2016-07-28 09:13
Dupe of #257?

Edit: Ninja'd yet again.

**Comment by Kolyall** [comment] 2016-07-28 09:36
Closed as duplicate

**Closed as completed** 2016-07-28 09:36 UTC
