### ISSUE TITLE
Flipping Screen Orientation Issue - Pokemon Found Stops Being Displayed

### ISSUE THREAD

**Issue by andycervantes** [omkarmoghe/Pokemap#202] opened 2016-07-26 19:22 UTC
After conducting several searches across the map, the text field on the bottom of the map will stop being displayed as the map is being populated with found Pokemon.

After further testing, it seems that changing the screen orientation causes the text display to stop being displayed.

**Comment by Giggitybyte** [comment] 2016-07-27 00:19
Can confirm. Upon rotating the screen, the label that displays how many Pokemon have been found will disappear.

**Comment by s7092910** [comment] 2016-07-28 00:28
I can't reproduce this. Anyone else?

**Comment by socrates2510** [comment] 2016-07-28 08:44
After flip horizontal the Snackbar is gone.

**Comment by Giggitybyte** [comment] 2016-07-28 10:09
Whenever PTC comes back up or Google login is reimplemented, I'll see if I can still get this to happen.

**Comment by chrosey** [comment] 2016-07-28 15:37
can't reproduce this error any longer. did somebody fix it?

**Comment by socrates2510** [comment] 2016-07-28 18:51
@chrosey can you confirm you are talking about the Snackbar notification? Pokémon will keep showing but not notifications.

**Comment by Giggitybyte** [comment] 2016-07-28 19:04
I was about to go test with the latest dev build when PTC went down. The Pokémon GO servers seem shaky, too. I can't wait for Google login to be functional again :(

**Comment by chrosey** [comment] 2016-07-28 19:57
@socrates2510 yup i meant the snackbar. but forget what i sad. it happens again.

I remember reading, that this may happen only on Samsung devices, can we prove that?
 maye i can find that post somewhere

Edit: read about [this bug on chromium project](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-reviews/Ov8rodCgUfw)

can this be related?

**Comment by socrates2510** [comment] 2016-07-28 20:04
It disappears in my Sony Xperia ZL, Android 4.4.4

**Comment by chrosey** [comment] 2016-07-28 20:39
having this issue also on samsung tablet (sm-p605)

Happening only on MapsFragment if i see it right. Double checked with loginActivity. if I rotate screen on LoginActivity there's no problem.

EDIT: if somebody has time, could you test it stops with replacing that static pokesnack with a not static one?

**Comment by s7092910** [comment] 2016-07-30 02:35
The thing is, the activity gets destroyed on rotation, so that snackbar also gets destroyed. That is why it keeps popping in and out.

So I would suggest that this one is closed

**Comment by chrosey** [comment] 2016-07-30 15:47
thats right. But far better than no Snackbar

**Comment by jakeyjdavis** [comment] 2016-07-31 09:25
Would this help at all? 
http://stackoverflow.com/questions/3329318/android-how-to-not-destroy-the-activity-when-i-rotate-the-device

**Comment by ManojMadanmohan** [comment] 2016-07-31 15:56
@jakeyjdavis thats a quick fix and will solve the issue, but its not the proper recommended way though. 

The right way to go about it would be to ensure activity recreation is handled properly in all cases. 
http://stackoverflow.com/questions/7818717/why-not-use-always-androidconfigchanges-keyboardhiddenorientation

**Comment by jLynx** [comment] 2016-08-27 01:21
Please re-open the issues if this is not fixed in the current release

**Closed as completed by jLynx** 2016-08-27 01:21 UTC
Labels: bug
