### ISSUE TITLE
Pokemon Go server disconnect constantly

### ISSUE THREAD

**Issue by ghost** [omkarmoghe/Pokemap#315] opened 2016-07-28 21:41 UTC
When logged in with a google account, it will find pokemons and keep saying that it's unable to connect to pokemon go servers rapidly while finding other pokemons. Quite weird.

**Comment by DoraKlikOpDora** [comment] 2016-07-28 21:43
Pokemon Go servers are hanging between up and down, this may cause this problem. Keep an eye on http://ispokemongodownornot.com and check if that is the problem.

**Comment by Sn3akySl0th** [comment] 2016-07-28 22:10
I'm having issues logging in using PTC. I have to hit sign in multiple times before it will actually go through.

**Comment by DoraKlikOpDora** [comment] 2016-07-28 22:30
@clefebvre81 Also look at the website http://ispokemongodownornot.com. The PTC login status is also given on that site.

**Comment by Sn3akySl0th** [comment] 2016-07-28 22:36
I was. When I try and it fails that is the first thing I look at. It has been saying up and I continue to have issues.

**Comment by fess89** [comment] 2016-07-29 09:51
@clefebvre81 this is a server problem, it may depend on where you are connecting from

**Comment by TDrakeHI** [comment] 2016-07-29 18:19
Sounds like this is a duplicate of #329.

**Comment by comann** [comment] 2016-08-12 20:01
No longer need login in upcoming release.

**Closed as completed by comann** 2016-08-12 20:01 UTC
