### ISSUE TITLE
Radius

### ISSUE THREAD

**Issue by Kibbols** [omkarmoghe/Pokemap#96] opened 2016-07-24 06:34 UTC
The scan radius is ridiculously small :/

**Comment by s7092910** [comment] 2016-07-24 07:00
We know, it is being worked on. Also duplicate Issue. See #92

**Comment by MikePT28** [comment] 2016-07-24 08:12
I propose we close this as it is duplicate.

Duplicate of #92 

@omkarmoghe

**Comment by Kibbols** [comment] 2016-07-24 22:14
Sorry, I couldn't really understand the OP of #92 that well.

**Comment by rohanjain1** [comment] 2016-07-25 10:12
-Close this please.
The search radius is not an issue, it's a side-effect of the fact that the project is still in progress. The Increased search radius is on our task list.

@Kibbols thank you for trying out the app and posting. The search area is our top priority as well, and don't tell anyone, but it's almost done ;)
Stay tuned.

**Closed as completed** 2016-07-25 21:40 UTC
