### ISSUE TITLE
No searchable Pokemon in Latest Build (297)

### ISSUE THREAD

**Issue by sheikhsabayyal** [omkarmoghe/Pokemap#210] opened 2016-07-26 21:22 UTC
Just installed the latest build and its showimg pokestops, gyms and scanning the area nut its showing 0.searchable pokemons. 

THE LOCATION IS Central.Park and there are always like hundreds of pokemom there atleast zubat etc.

**Comment by Anu6is** [comment] 2016-07-26 21:28
Confirmed. It appears that the previously added filter "Pokemon to Show" is not being populated. As such there are no valid Pokemon to show.

[UPDATE] It appears that the list takes some time to populate. Once populated, the app works as expected.

**Comment by blastagator** [comment] 2016-07-26 21:37
dev-rev272 works, fyi

**Comment by GiantForkLift** [comment] 2016-07-26 21:39
Can confirm that dev-rev272 is the only latest version that works properly with the scan feature. Every build after that has failed to search.

**Comment by kyr0** [comment] 2016-07-26 21:56
Hrm. Why does it work for me than?

**Comment by Anu6is** [comment] 2016-07-26 22:02
@kyr0 
Like I said, the filter list does load after some time. 
And it appears to persist once loaded. I've closed off and re-opened the app and the list is available now from start-up.

**Comment by blastagator** [comment] 2016-07-26 22:05
Confirmed - strange but true.  Closed and reopened app and works now.

**Comment by rbryson74** [comment] 2016-07-26 22:55
I also found that opening the filter list and then restarting the search works ok.

**Comment by Giggitybyte** [comment] 2016-07-27 00:14
Still happening in development build 309. Takes a few app restarts for it to finally work.

**Comment by GiantForkLift** [comment] 2016-07-27 04:26
Looks like the issue is fixed in the latest build, 321. Thanks for the help/suggestions on this!

**Closed as completed** 2016-07-27 14:16 UTC
