### ISSUE TITLE
Find no Pokemons 

### ISSUE THREAD

**Issue by momo0206** [omkarmoghe/Pokemap#383] opened 2016-07-31 11:15 UTC
Since the last update, the app show me only few pokemons. With another app like "pokevision" i found more. Can someone tell me why the app found no Pokemons?

**Comment by kitohiro** [comment] 2016-07-31 14:01
pokevision doesn't work, read older post... it's since the last update, all tracker app/website are down.

**Comment by Ayysir** [comment] 2016-07-31 14:58
They shut down API access

**Comment by momo0206** [comment] 2016-07-31 15:03
And i think there is noch way to fix it?

**Comment by momo0206** [comment] 2016-07-31 15:03
*no

**Comment by antony1316** [comment] 2016-07-31 16:08
Not sure if it's totally shutdown. The AHAAAAAAA/PokemonGo-Map project still works on my PC. That's the project this port was based on. So what's the difference is the question?

**Comment by programmerpro19** [comment] 2016-07-31 16:10
I think they reduced the scan radius, so we just need to make a few changes to the config in MapHelper.

**Comment by rbryson74** [comment] 2016-07-31 17:08
There is also now the issue of the scan frequency. Niantic has throttled the api so each single account can only scan once every 5 seconds. Otherwise the scan comes back blank. I have had to switch to using a fractured multi-account python server from the AHAAAAAAA project instead of this app. :(

**Comment by Cyb4Black** [comment] 2016-07-31 19:38
Can someone tell me where you handle the search loop? So I'd like to test if adding a delay between steps could help.

**Comment by pillisan42** [comment] 2016-07-31 20:32
Hey I've written a little workaround due to this problem it's slows down scan but i have made the scan running in background and refresh the activity on resume with data coming from the service.

For now it take 120 seconds to refresh the area around you. 

I adjusted Notifications as well

**Comment by pillisan42** [comment] 2016-07-31 20:35
I have made a fork and push my changes https://github.com/pillisan42/Pokemap
I have tested this afternoon and it work quite well everytime pokemap find pokemon around me without missing one (it's just slow)

**Comment by mastescarhead1** [comment] 2016-07-31 20:40
^ can you compile an apk for ust to test?

**Comment by pillisan42** [comment] 2016-07-31 20:45
Yeah let me 10 min to get back home and i'll send you that. (There was tentacruel level 1200) juste 300 meters from my home i had to get it )

**Comment by pillisan42** [comment] 2016-07-31 20:56
Here it is
Just so you know you have to start log yourself then restart the application.
Otherwise the service won't start on the first start 
I don't have figure it out for now. I think it's nothing but I was focusing on something else.

[app-debug.zip](https://github.com/omkarmoghe/Pokemap/files/392636/app-debug.zip)

oh i forgot, you just have to rename app-debug.zip to app-debug.apk

**Comment by pillisan42** [comment] 2016-07-31 20:57
oh i forgot, you just have to rename app-debug.zip to app-debug.apk

**Comment by pillisan42** [comment] 2016-07-31 21:13
Well it seems i have a big problem with parameters you have to go in parameter activity before restart the application so that the service work on the next restart ...
Sorry for that i'm working on a fix

**Comment by pillisan42** [comment] 2016-07-31 21:17
[app-debug.zip](https://github.com/omkarmoghe/Pokemap/files/392651/app-debug.zip)
Just fixed it :)

**Comment by monu11296** [comment] 2016-07-31 21:24
@pillisan42 have you pushed your latest changes to your fork ?

**Comment by pillisan42** [comment] 2016-07-31 21:26
Just done it

**Comment by magiblot** [comment] 2016-07-31 21:57
@pillisan42 Crashes upon start for me, with Android 4.4.2

**Comment by pillisan42** [comment] 2016-07-31 22:01
@magiblot have you some trace to provide ? Which language are you using it may be the cause i have not updated any language just english and french the problème may come from there

**Comment by magiblot** [comment] 2016-07-31 22:12
@pillisan42 Spanish. Yes that might be the problem.

**Comment by pillisan42** [comment] 2016-07-31 22:18
@magiblot i tried it with spanish version and i had no crash but i've got a 6.0.1 version 

Can you provide me your traces ?

**Comment by magiblot** [comment] 2016-07-31 22:19
@pillisan42 Sorry, I'm not a programmer. I don't know what traces are nor how to see them.

**Comment by Giggitybyte** [comment] 2016-07-31 22:25
@pillisan42 I pulled from your fork and built my own APK. It runs for me and I can login successfully. However, scanning doesn't seem to work at all. Also, the background notification seems very broken does not seem to want to go away.

I can provide logcats if needed. I am running 5.1.1.

**Comment by pillisan42** [comment] 2016-07-31 22:33
@magiblot I'm sorry for you i can't help you without any traces. Try to get logcat with https://play.google.com/store/apps/details?id=com.pluscubed.matlog. Otherwise you will have to wait a little or try with another phone. I hope it will be fixed in the near future for you.
@Giggitybyte On my phone it work pretty well it just take some time 3 step scanning take 120 seconds approximately. I recommend to adjust it to 1 step scanning. If you want to make scan somewhere else. I also recommend to deactivate background service then restart the application too. If i'm not wrong when you force scan it should stop previous scan you have initiated.

Yeah you can send them I'll take a look at them.

**Comment by magiblot** [comment] 2016-07-31 22:37
@pillisan42 I'll try to do it anyway.
EDIT: I don't have Superuser access, so I'll wait until tomorrow to fix it by using the Android SDK. I'll try the app in Bluestacks meanwhile, and as it is rooted, I'll share logs with you if I find any problem.

**Comment by magiblot** [comment] 2016-07-31 23:21
@pillisan42 Crashed upon start on BlueStacks 0.10.0.4321, here's the log:
http://pastebin.com/D30zNQ0N
I share it because the bug causing the crash might be the same that ocurred in my mobile phone. I'll try to take the log from my mobile phone tomorrow.
EDIT: This version works both on Bluestacks and my mobile phone --> https://github.com/omkarmoghe/Pokemap/releases/tag/dev-rev527

**Comment by pillisan42** [comment] 2016-07-31 23:28
Oh i see it's because i've build the application with instant run and it's a multidex application that is only compatible with version 5.0.0 and older ... sorry for that I'm building a version without instant run right now

**Comment by pillisan42** [comment] 2016-07-31 23:32
This one should work on 4.x.x version
[app-debug.zip](https://github.com/omkarmoghe/Pokemap/files/392702/app-debug.zip)

**Comment by magiblot** [comment] 2016-07-31 23:39
@pillisan42 Okay, runs properly now. Does it work better than omkarmoghe version?

**Comment by mastescarhead1** [comment] 2016-08-01 03:15
Yah, I found it runs smoother than this version. 
I still think we need an alternative method though. This is way too slow, and it we do it at this speed, you'd never catch the pokemon in time

**Comment by programmerpro19** [comment] 2016-08-01 04:08
So the main project https://github.com/AHAAAAAAA/PokemonGo-Map has a fork where someone's made it so you can give the application multiple usernames/passwords and it cycles through that, in essence, if you create 10accounts, you could request data for 1 point every 0.5seconds.

**Comment by mastescarhead1** [comment] 2016-08-01 04:09
^ I have been using it. I think we should just do that for Pokemaps. Just allow section to add accounts

**Comment by s7092910** [comment] 2016-08-01 04:11
@programmerpro19 @mastescarhead1 we are looking at that. But we are working on a solution that won't require you to login at all to use the app. I can't go into much more detail about it.

**Comment by zorakirby** [comment] 2016-08-01 05:13
link to the AHAAAAAAA fork?

**Comment by s7092910** [comment] 2016-08-01 06:48
@zorakirby at this time the core team won't be sharing this fork till we are 100% getting it working the way we want it to.

**Comment by pillisan42** [comment] 2016-08-01 06:57
@mastescarhead1 yeah you have to wait à certain amount of time before the l'application warn you about the présence of a pokemon but i find this solution adaptée when you are walking and searching them around 300 meter i have imagines it to be an alternative to the steps functionality and when a new pokémon is détectée you have at least 13 min to catch it. 

@s7092910 that would be Nice if we dont have to login at all :) i'm looking for to see your version

**Comment by magiblot** [comment] 2016-08-01 14:41
The app is already very useful in its current state. Instead of doing a massive scan of your area and then decide which Pokémon you want, you play the game as usual, and when an interesting Pokémon appears in the "nearby" list, you analise the area to locate it.

This seems to me more fair than using the app to get the location of all the Pokémon. It is fair because it just works as a replacement of the broken footprint system (due to this bug, you usually don't find the interesting Pokémon from the list). Oppositely, I don't entirely agree with getting a complete positioning of all the Pokémon in a few seconds. In my opinion, that makes the game much less funny. For example, it removes the luck factor of getting good Pokémon by surprise. Instead, it turns the game more mechanical and makes it lose its sense. (Hey, and I am not against your work; as you can see, one of the first things I have wanted to do is to try out the app myself. Those were just my feelings about this topic).

Oh, but please beware of the login methods you come up with. If Niantic really wants to take down this kind of applications (and punish their users, because otherwise they will always find a way to get advantage), they will do so, most probably. If detecting the accounts that are used to get the location of the Pokémon becomes useless because they aren't the ones the offenders play with, Niantic won't hesitate to make bans based on IP adress (the ban of all the accounts that have been used from the same IP adress). If this happens, avoinding the ban will turn out to be like using a second mobile phone for the positioning app or using VPNs within the mobile phone (which seems a little crazy to me). So... be careful (avoiding login might be a solution, but then we should prevent our IP from being recognized).

**Comment by mastescarhead1** [comment] 2016-08-01 14:48
@magiblot I completely disagree with your assessment. First off, you can't even scan around your area currently because the scan interval will return empty. So in its current state, you cannot use the app even if it's like you are saying. 
Secondly, I think it's up to the user how they want to use the app. If Niantic really wants to crack down, which I don't think they will (considering the backlash they've got for this current update, including financial loss due to people getting refunds due to the broken 3-step removal), they probably would have learned their lesson

**Comment by magiblot** [comment] 2016-08-01 15:10
@mastescarhead1
No, in spite of the low scanning speed, I still can use it. In fact, I have sent this picture to a friend of mine this morning and has been able to catch the Bulbasaur: http://imgur.com/uYzsJke

Regarding my opinion, I just felt like writing it. I wasn't expecting it to be the same as yours nor to make you agree with me. I haven't written it in order to argue with you.

**Comment by mastescarhead1** [comment] 2016-08-01 15:11
@magiblot Are you talking about the version pillisan42 made? Because the main dev releases scan several times a second and return empty

**Comment by magiblot** [comment] 2016-08-01 15:12
@mastescarhead1 Yes, pillisan42's version works properly. The only drawback is that each of these yellow circles takes 5 or 6 seconds to load.

**Comment by pillisan42** [comment] 2016-08-01 15:33
@magiblot Thank you i'm glad this version suit you. By the way I fixed some other things that why it may look to work better. 

@mastescarhead1 
I used it today and i saw two main problem in my version : 
- You have to wait Two cycles of 120 seconds before it start to display pokemon around
- sometimes the background service stop to fetch remote pokemon.
  But like magiblot i suceed to find a Bulbasaur and a Squirtle that was around me

**Comment by magiblot** [comment] 2016-08-01 15:41
@pillisan42 "You have to wait Two cycles of 120 seconds before it start to display pokemon around"
Mhmm I don't (always) have that problem. I'll show it to you later, I get to go now.

**Comment by jomarocas** [comment] 2016-08-01 17:03
@pillisan42 You can compile the app please? i dont have android studio in this moment and take normally more that one hour please, thanks

**Comment by pillisan42** [comment] 2016-08-01 17:34
@magiblot Well notification will start display pokemon when the second cycle will start if you put the MapActivity on pause

@jomarocas there is a compiled version just up there if you want (you have to change .zip to .apk)

**Comment by sngreco** [comment] 2016-08-01 20:25
@pillisan42 I like what you've done there with your version, it seems like a good workaround.  Might I suggest adding multiple logins so that you could have multiple threads?  This could be implemented in parallel starting points for multiple scans or just increase the speed of the iniital scan around your selected point.  I kind of like the idea of having multiple scan points because my neighborhood is a long odd shape and the circular pattern covers mostly grass area instead of the paved area where the spawn points are.

**Comment by zorakirby** [comment] 2016-08-01 21:44
>  programmerpro19 commented 18 hours ago
> 
> So the main project https://github.com/AHAAAAAAA/PokemonGo-Map has a fork where someone's made it so you can give the application multiple usernames/passwords and it cycles through that, in essence, if you create 10accounts, you could request data for 1 point every 0.5seconds.<

Link to this fork?

**Comment by ervinpapp** [comment] 2016-08-02 07:42
@pillisan42 First of all, thank you for your app! I really like this app, and the settings options are great. I found only one strange thing: there is no pokemon in the center cirlcle of the search area. Detects all the surrounding pokemon, but none in the "first" circle. Did you or anyone else experienced this? (I'm on android 6.0.1.)

**Comment by Cyb4Black** [comment] 2016-08-02 12:53
@ernyo same here. S5 on 6.0.1

**Comment by Eg1M** [comment] 2016-08-02 17:13
Unfortunately, your version of the app still did not solve the problem with disappeared Pokemons. Android 6.0

**Comment by allard1997** [comment] 2016-08-02 20:35
Having the same issue as @ernyo about pokemons not being found in the first scanned circle and it also doesnt work if you set the scan range to 1 in the settings. If I set the scan range to 2 in the settings and then place the starting scan point under the first scanned circle the pokemons do spawn on that position.

**Comment by magiblot** [comment] 2016-08-03 22:56
@pillisan42 The app no longer detects any Pokémon

**Comment by zorakirby** [comment] 2016-08-03 23:17
can someone update the Pokemon Go Api calls? I personally don't know how any of the that stuff works

**Comment by s7092910** [comment] 2016-08-03 23:31
Pretty much Niantic changed something with the server responses or possibly even changed the API domain. The team is working on getting this fixed. But it will require some work. We are also seeing if anyone has implemented a fix yet.

**Comment by leovarmak** [comment] 2016-08-04 04:10
@pillisan42 Hey, I am using 6.0, have you got any release version for me ? :)

**Comment by mastescarhead1** [comment] 2016-08-04 05:09
@leovarmak  ^ 6.0 works with the files he posted above. 

@s7092910 could we not just sniff the target of the updated pokego app? Even if the API domain changed, the equivalent of sharkwire should be able to sniff it out.

**Comment by Ramiloom** [comment] 2016-08-04 13:08
This web (and ios app): https://map.goradar.io/
Still works! I wonder how?

**Comment by mastescarhead1** [comment] 2016-08-04 14:37
@Ramiloom doesn't work for me

**Comment by sngreco** [comment] 2016-08-04 14:37
@Ramiloom I tried that site but I can't seem to get it to update the location from Santa Monica Pier.  Tried both Chrome and IE.

**Comment by aripjanovsh** [comment] 2016-08-05 11:28
This web https://skiplagged.com/pokemon works to

**Comment by momo0206** [comment] 2016-08-05 11:35
Also in Germany ?@aripjanovsh

**Comment by magiblot** [comment] 2016-08-05 12:42
These websites are crowdsourced. This means they don't use the Niantic API - they don't get the information from Pokémon GO servers, which is what Pokémap and Pokévision used to do.

The update has forced the developers to reverse-engineer the game again and develop a fixed API, so we'll have to wait until then.

The following page shows the progress made up to now:
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by magiblot** [comment] 2016-08-07 01:27
@omkarmoghe @pillisan42 A new API is avaiable at https://github.com/keyphact/pgoapi . Theoretically you only have to grab the source from the link and update the API calls in whatever implementation you are using and you should be good to go.

**Comment by s7092910** [comment] 2016-08-07 06:58
@magiblot We are already hard at work on it. We are just figuring out what fields are absolutely required and which ones are needed to have it be less likely to get the account banned. Also we have to wait a bit for one of the libraries that we use to add in the new Proto.

**Comment by Jaruba15** [comment] 2016-08-07 15:58
pokemap live 1.31 is allready working...

**Comment by GaurAfro** [comment] 2016-08-07 17:37
When will the apk be deposited?

**Comment by magiblot** [comment] 2016-08-07 18:11
@Jaruba15 As far as I know, that version was released before the new API was released. Am I wrong?

**Comment by Jaruba15** [comment] 2016-08-07 18:19
@magiblot i think so, but the app is working perfectly

**Comment by Jaruba15** [comment] 2016-08-07 18:21
@magiblot pokemap live 1.31 Update: 2016-08-02

**Comment by magiblot** [comment] 2016-08-07 18:21
@Jaruba15 Does it require login?

**Comment by Jaruba15** [comment] 2016-08-07 18:23
@magiblot yes it needs a login with google

**Comment by magiblot** [comment] 2016-08-07 18:30
@Jaruba15 Seems worth giving it a try. However, I suspect it could be easier to get banned if it doesn't use the fixed API.

**Comment by Jaruba15** [comment] 2016-08-07 18:40
@magiblot yes it could happen, but i use a different account for pokemap and pokemon go, so if the ban the one from pokemap i can still play pokemon go.

**Comment by xakiru** [comment] 2016-08-07 18:43
What pokemap live 1.31 are you talking about ?

**Comment by magiblot** [comment] 2016-08-07 18:48
I think it's this one:
[com.skiplagged.pokemap_1.31.zip](https://github.com/omkarmoghe/Pokemap/files/405655/com.skiplagged.pokemap_1.31.zip)
(Rename to .apk)

**Comment by xakiru** [comment] 2016-08-07 19:00
It doesn't work for more than 30 seconds for me ...

**Comment by magiblot** [comment] 2016-08-07 19:04
Actually it works for me, I have compared the results with PokémonGo-DesktopMap, and they matched.
But I don't like the fact I can't see the scanned area and that I can't find the app here in GitHub.

**Comment by Jaruba15** [comment] 2016-08-07 19:09
i tested it today, i was in a park for 6 hours and found every single pokemon.

**Comment by mastescarhead1** [comment] 2016-08-07 19:10
The skiplagged website works a lot better than the scanning apps imo
I guess they have a server on their end which does all the scannings
That way it's less data usage, as well as faster results

**Comment by Jaruba15** [comment] 2016-08-07 19:12
@mastescarhead1 the skiplagged website is not working for me but the app is working.

**Comment by magiblot** [comment] 2016-08-07 19:16
The skiplagged website is crowdsourced, so it only works in certain big cities. Oppositely, you can log in to the app, so I guess it just takes the data from the server and works wherever you are.

**Comment by mastescarhead1** [comment] 2016-08-07 19:19
@magiblot I doubt the skiplagged website is crowdsourced. It has pokemons that are at 14:30 sec, and it's really accurate, as in every single pokemon
I think they may just have a scanner that scans the major cities

**Comment by xakiru** [comment] 2016-08-07 19:19
So they fixed the unknown 6 packets before 2016-08-02 ?

**Comment by Jaruba15** [comment] 2016-08-07 19:20
@magiblot @mastescarhead1 seems so, the website is working in some big cities but not everywhere.

**Comment by magiblot** [comment] 2016-08-07 19:21
@xakiru Maybe the app is server-depending and they just had to update the API in their server. If it had worked before the fixed API we would have known it for sure.

**Comment by mastescarhead1** [comment] 2016-08-07 19:23
The app is definitely server dependent. I mean the app is still utilizing skippedlag server
I think what it is doing is simply pulling data from the skipplagg server, which in turn is scanning the pogo servers with several accounts fixed in certain cities

**Comment by xakiru** [comment] 2016-08-07 19:24
I tried the app days ago, and it was either crashing, or not working.

**Comment by s7092910** [comment] 2016-08-07 19:24
@mastescarhead1 It is crowdsourced. But it does it in a different way that having people manually input the locations. What they are doing is running a lot of emulators that have a modified version of the pokemon go app. This modified version allows them to intercept and read the in coming data. That data is then put on a server.

**Comment by mastescarhead1** [comment] 2016-08-07 19:26
@s7092910 so essentially it would have the same efficacy as scanning then, since the scan rate is maxed at once per 5 sec, no? So perhaps their method is actually more accurate in getting pokemons as soon as they pop up?

**Comment by magiblot** [comment] 2016-08-07 19:56
@mastescarhead1 
No. It seems to me that this app provides both scanned (throught our account) and crowdsourced (scanned by others) information.

**Comment by s7092910** [comment] 2016-08-07 20:33
@mastescarhead1 Yes and no. Currently we are working on showing all the pokemon that are catchable. All the others have issues where certain pokemon that have spawned will not show up on the map.

**Comment by s7092910** [comment] 2016-08-08 04:07
Just so you guys know, there is some important news in the ReadMe.md. This is one of the reasons why we are taking a bit longer. As one of the changes has to build our own implementation for the PokemonGo Api.

**Comment by mastescarhead1** [comment] 2016-08-08 05:39
Do we have an ETA?

**Comment by programmerpro19** [comment] 2016-08-08 07:05
Further development of Pokemap will continue in a private repo. The source code here will be left as legacy.

How do I join the "Private Repo" and help?

**Comment by CarstenHouweling** [comment] 2016-08-08 09:30
@programmerpro19 I also want to continue working on my directions/navigation stuff for Pokémap. I also keep the Dutch translations up to date. How to join the Private Repo?

**Comment by magiblot** [comment] 2016-08-08 12:36
Again, finds no Pokémons for me. Settings: Show lured Pokémon: ON, Show scanned area: ON, Search Size: 5, Background Service: OFF. Logged in using Google account. dev-rev538

Catlog: http://pastebin.com/d41iVr90
Screenshot: http://imgur.com/F9ylJTN

EDIT: Re-reading your last post, s7092910, I have realized this new development build could not be supposed to work, because you have not finished with the API implementation yet.

**Comment by axsddlr** [comment] 2016-08-09 00:07
@programmerpro19  me 3, I want to use my dev experience and contribute code

**Comment by s7092910** [comment] 2016-08-09 04:23
@magiblot The apk that filfat uploaded was still of the old build. Which it seems that filfat might have set up a bot that will do an apk build from the github repo whenever there is an update to the repo. So that would be an apk build of the old code.

We are actually getting very close to having a build that is ready. We fixed one issue that was plaguing us for the past day or so.

**Comment by jLynx** [comment] 2016-08-10 10:55
We are possibly a day or so away from release. The hype is real!

**Comment by blackmaskmen** [comment] 2016-08-10 18:42
Can anyone Send me the working apk??

**Comment by CarstenHouweling** [comment] 2016-08-10 19:05
@blackmaskmen no, sorry. We're all out off apk's.

**Comment by blackmaskmen** [comment] 2016-08-10 19:11
@CarstenHouweling Ohh no!! So old app won't work anymore uh??

**Comment by CarstenHouweling** [comment] 2016-08-10 19:14
@blackmaskmen I'm afraid the old server gods have abandoned us :(

**Comment by blackmaskmen** [comment] 2016-08-11 14:20
Guys Any luck?? Any good news!!

**Comment by mastescarhead1** [comment] 2016-08-11 15:09
@blackmaskmen take a chill pill. They will update when they have an update

**Comment by jLynx** [comment] 2016-08-11 19:03
_Guys we have it fully working and are only days away from releasing it now_

**Comment by CarstenHouweling** [comment] 2016-08-11 19:10
Good to hear! Can i submit pull requests to the private repo? I have navigation implemented.

**Closed as completed** 2016-08-13 18:19 UTC
