### ISSUE TITLE
FATAL EXCEPTION: Niantic Manager Thread

### ISSUE THREAD

**Issue by Kolyall** [omkarmoghe/Pokemap#131] opened 2016-07-25 08:09 UTC
- Run the app
- Log in
- Long click on the map
- bug: crash

suggestion : change Thread to RxJava observable with backgroundThread to avoid crashes

```
FATAL EXCEPTION: Niantic Manager Thread
                                                                        Process: com.omkarmoghe.pokemap, PID: 22647
                                                                        java.lang.RuntimeException: Generated message class "POGOProtos.Map.Fort.FortDataOuterClass$FortData$Builder" missing method "getId".
                                                                            at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1806)
                                                                            at com.google.protobuf.GeneratedMessage.access$1100(GeneratedMessage.java:61)
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessage.java:2095)
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessage.java:2694)
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessage.java:1944)
                                                                            at POGOProtos.Map.Fort.FortDataOuterClass$FortData.internalGetFieldAccessorTable(FortDataOuterClass.java:327)
                                                                            at com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:108)
                                                                            at com.google.protobuf.AbstractMessage.equals(AbstractMessage.java:119)
                                                                            at java.util.ArrayList.remove(ArrayList.java:418)
                                                                            at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:190)
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:312)
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250)
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185)
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
                                                                            at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:101)
                                                                            at com.omkarmoghe.pokemap.controllers.net.NianticManager$8.run(NianticManager.java:284)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         Caused by: java.lang.NoSuchMethodException: getId []
                                                                            at java.lang.Class.getMethod(Class.java:630)
                                                                            at java.lang.Class.getMethod(Class.java:609)
                                                                            at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1804)
                                                                            at com.google.protobuf.GeneratedMessage.access$1100(GeneratedMessage.java:61) 
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessage.java:2095) 
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessage.java:2694) 
                                                                            at com.google.protobuf.GeneratedMessage$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessage.java:1944) 
                                                                            at POGOProtos.Map.Fort.FortDataOuterClass$FortData.internalGetFieldAccessorTable(FortDataOuterClass.java:327) 
                                                                            at com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:108) 
                                                                            at com.google.protobuf.AbstractMessage.equals(AbstractMessage.java:119) 
                                                                            at java.util.ArrayList.remove(ArrayList.java:418) 
                                                                            at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:190) 
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:312) 
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250) 
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185) 
                                                                            at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175) 
                                                                            at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:101) 
                                                                            at com.omkarmoghe.pokemap.controllers.net.NianticManager$8.run(NianticManager.java:284) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by s7092910** [comment] 2016-07-25 09:16
It has been discussed we won't be using RxJava. It would still have a crash in RxJava too.

**Comment by dekefake** [comment] 2016-07-25 17:04
I think the problem is just before. Look oemlogkit errors. I didn't digged into app sources, but maybe thats that. Furthermore, it seems to happen when many Pokemon are detected. It works well in my small town, but as soon as I long press my city center 10kms away, it crashes instantly.

Look my logcats here http://m.imgur.com/bqVTNR1
'
Edit : maybe oemlogkit comes from my phone, and not the app

**Comment by Kolyall** [comment] 2016-07-25 19:03
@dekefake the bug was when i tried to make a new Search(long click), without waiting for previous Search results

**Comment by mastescarhead1** [comment] 2016-07-25 20:02
^ I can verify this. Causes issues when there are too many pokemon around
r200 now incorrectly flags this as internal error (offline or server down)
Servers are functioning because python script sees them, as well as less-pokemon populated regions are working

**Comment by comann** [comment] 2016-07-26 14:32
@kyr0 Isn't this fixed in the latest dev?

**Comment by mastescarhead1** [comment] 2016-07-26 17:27
Yah, this is fixed. First it was a try catch with the internal error. 
Now, that's been taken care of as well
We should probably close this thread.

**Closed as completed** 2016-07-27 14:31 UTC
Labels: bug
