### ISSUE TITLE
PTC Login Failed on first start up

### ISSUE THREAD

**Issue by RainFromAClearSky** [omkarmoghe/Pokemap#442] opened 2016-09-01 09:25 UTC
I downloaded  1.1.4 and installed. Started the app for the first time, successfully got the the page where it explains that there'll be 10 captchas to solve. 

Move to the next screen and flashes up a "PTC Login Failed" message along the bottom on the screen in a grey bar. This shows twice (second time lasts alot longer so maybe this is overlapping notifications for several attempts)

Successfully manually created a PTC account on the website to show that the PTC account creation page is not down.

Tried the app again with the same result, left it on for 10 minutes with no change.

Cycled phone airplane mode on/off checked to make sure I got a new IP address, tried the app again - same result.

Samsung Galaxy S5 running Android 5.0.2

Edit: And I'm in Europe if that makes a difference...

**Comment by Genome-1** [comment] 2016-09-01 12:54
Same issue here. Exactly as you described, the message pops up once briefly and then again for a longer time. 

Tried restarting. Tried upgrading firmware. Tried downloading from github and from the website. Tried running while PG was open and closed. Still doing exactly the same thing.

Using a Sony Xperia Z3, was running a 5x version, just upgraded to 6.0.1 in case that was the issue.

**Comment by jLynx** [comment] 2016-09-01 17:07
Seems the server went down temporarily, it should be up now. Let me know if the app is working now for you

**Comment by RainFromAClearSky** [comment] 2016-09-01 17:28
I'm still seeing the identical behaviour (PTC Login Failed messages)

**Comment by Genome-1** [comment] 2016-09-01 17:32
Same here. Before the reddit thread got taken down, it looked like a lot of people on there were having the same issue.

**Comment by infoman5** [comment] 2016-09-01 21:19
I just installed the 1.1.4 release and I have the same issue.

**Comment by canpoke** [comment] 2016-09-01 21:28
Exactly the same issue for me too. V1.1.4

Using SMG900W8 (S5) on 6.0.1.

**Comment by jLynx** [comment] 2016-09-01 21:32
We are looking into this issue now. If one of you doesn't mind, can you clear the app data and redo the captchas to see if that fixes it? If it does I might have an idea what's happening

**Comment by infoman5** [comment] 2016-09-01 21:35
It does not allow you to do the captchas since it gets stuck after the PTC Login Failure message.

**Comment by canpoke** [comment] 2016-09-01 21:37
I don't even get an attempt at completing captchas.

Cleared all app data and restarted the app.
Get the captcha explanation welcome screen > click 'Done'
Get the prompt for access to location > Allow
Get PTC login failed msg
From here the app doesn't do anything and has no options.

**Comment by RainFromAClearSky** [comment] 2016-09-01 21:38
OK, so the original problems prevents you ever getting as far a completing the captchas - the PTC Login Failure happens first.

But clearing the app data didn't stop the PTC Login Failure messages for me - just like canpoke explained.

**Comment by jLynx** [comment] 2016-09-01 21:39
@canpoke thank you, I think I have a  idea for what is going on. Look out for an update in a a few hours (hopefully)

**Comment by RainFromAClearSky** [comment] 2016-09-01 21:40
@DarkN3ss61 great news - thank you

**Comment by infoman5** [comment] 2016-09-01 21:42
@DarkN3ss61 Fastest developer response I've ever seen!

**Comment by jLynx** [comment] 2016-09-02 04:36
Sorry guys have been a but busy, might be a bit longer before I get the update out, I will see if any of the others developers could take care of this sooner

**Comment by s7092910** [comment] 2016-09-02 07:25
It has been a long day for a lot of us. I found what the issue is. I'll be fixing it tomorrow.

For now there is a work around. 
1. Clear the app cache
2. Start the app
3. Do not press Done.
4. Wait a second or two. Make sure you have a good internet connection.
5. Done should change to next after a short bit or you will be taken to the splash screen. Skip step 6 and 7 if it takes you to the splash screen.
6. Hit next
7. Complete the Captchas.
8. Wait at the Splash Screen
9. Enjoy the app

**Comment by Genome-1** [comment] 2016-09-02 07:58
Reinstalled to get back to the startup screen, waited for 10m, done didn't change for me. Step 5 a no go! Guess I'll just have to wait for the fix.

**Comment by RainFromAClearSky** [comment] 2016-09-02 08:41
Firstly, thank you for looking into this in such a timely fashion.

I have the same experience as @Genome-1 , I can clear app data or re-install to get back to the screen with 'done' at the bottom but no amount of waiting changes that screen. I never get to step 5 in your list, the screen always says 'done', even after 10+ minutes of waiting.

**Comment by canpoke** [comment] 2016-09-02 16:15
Thanks for your efforts!

Unfortunately waiting also never gets me past the "Done" prompt on the "Welcome to Pokemap" screen.

**Comment by infoman5** [comment] 2016-09-02 19:25
@s7092910, When I follow the steps you provided I also am unable to get past Step 5
1. Clear the app cache 
   Done
2. Start the app 
   Done
3. Do not press Done. 
   I don't press the Done button
4. Wait a second or two. Make sure you have a good internet connection. 
   I have a good internet connection and wait.
5. Done should change to next after a short bit or you will be taken to the splash screen. Skip step 6 and 7 if it takes you to the splash screen. 
   Done never changes to next no matter how long I wait.

**Comment by s7092910** [comment] 2016-09-02 21:29
Thanks for letting me know. It seems I was a bit wrong with what went wrong. It should be fixed in the next couple of hours.

**Comment by skylex77** [comment] 2016-09-03 01:17
Yeah I have the same problem, what I do was to install the v1.1.1 and then complete the captcha, then the app ask to update I download it from that link, then I install the 1.1.4 and works :)

**Comment by canpoke** [comment] 2016-09-03 01:47
This worked for me as well. 
-Uninstalled 1.1.4
-Installed 1.1.1
-Got the 10 captcha prompts this time and completed them
-App then asks me to update to V6.0 (??) and redirects to pokemapgo.xyz
-Installed 1.1.4
-Opened app and it loaded up properly

Thanks!

**Comment by jLynx** [comment] 2016-09-03 01:49
V6.0 Is 1.1.4. We have fixed I'm that in the 1.1.4, it was getting the code version not the name

**Comment by s7092910** [comment] 2016-09-03 01:58
Update coming that will fix this issue.

**Comment by jLynx** [comment] 2016-09-03 02:03
Update is here https://github.com/omkarmoghe/Pokemap/releases/download/v1.1.5/PokeMap_1.1.5.apk

This should fix the issue

Edit, try 1.1.6

**Comment by skylex77** [comment] 2016-09-03 02:49
![2016-09-02_204318](https://cloud.githubusercontent.com/assets/20802056/18222251/b6f6807a-714e-11e6-8ff6-8b2e858db63a.jpg)

**Comment by infoman5** [comment] 2016-09-03 02:58
Got the same error as skylex77.  I then tried @canpoke instructions above and it's working fine for me now.

**Comment by s7092910** [comment] 2016-09-03 04:07
Looking into it right now.

**Comment by Genome-1** [comment] 2016-09-03 04:15
'Got the same error as skylex77. I then tried @canpoke instructions above and it's working fine for me now.'

**Comment by jLynx** [comment] 2016-09-03 04:28
Fix in 1.1.6

https://github.com/omkarmoghe/Pokemap/releases/download/v1.1.6/PokeMap_1.1.6.apk

**Closed as completed by jLynx** 2016-09-03 04:28 UTC

**Comment by RainFromAClearSky** [comment] 2016-09-03 07:26
THANK YOU!
