### ISSUE TITLE
First time that you login with google account fails.

### ISSUE THREAD

**Issue by Xelwon** [omkarmoghe/Pokemap#338] opened 2016-07-29 14:50 UTC
First time that you login with google account fails, but you try a second time and it goes well.

It happens always that you close the app and open it again (without proccess runnig.)

**Comment by Giggitybyte** [comment] 2016-07-29 18:38
Dupe of #330??

**Comment by comann** [comment] 2016-08-12 19:58
App no longer has user login.

**Closed as completed by comann** 2016-08-12 19:58 UTC
