### ISSUE TITLE
Not showing Pokestops

### ISSUE THREAD

**Issue by NozderkaJakub** [omkarmoghe/Pokemap#394] opened 2016-08-01 11:25 UTC
The pokemap doesn't show pokestops (with option enabled in settings) since update 0.3

**Comment by LinkOut** [comment] 2016-08-01 13:32
Duplicate of #383

**Comment by NozderkaJakub** [comment] 2016-08-01 14:37
@LinkOut 
#383 is about not showing pokemons

**Comment by robinodling** [comment] 2016-08-01 15:30
My experience is that pokestops show up sometimes, and sometimes not.. Most often the latter.

**Comment by juanro49** [comment] 2016-08-01 17:53
I have same problem, since lastest updates, pokestops doesn't swow :(

**Closed as completed** 2016-08-27 01:12 UTC
